### ISSUE TITLE
Remove lock image and keep only blurred images.

### ISSUE THREAD

**Issue by chhajedji** [petvas/i3lock-blur#8]
I have been using this lock since a long time and really love it. But while using it with multiple monitors of uneven sizes, lock image appears somewhere in between the monitors which looks ugly. How will the `ffmpeg` command change if I want to remove the lock image and only keep the blurred images?

**Comment by petvas** [comment]
remove the input: `-i $LOCK` and the overlay part from the filter.

**Comment by chhajedji** [comment]
Thanks, this worked just fine. 😃

```diff
-ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=10:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet
+ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -filter_complex "boxblur=10:1" -vframes 1 $TMPBG -loglevel quiet
```
